### ISSUE TITLE
Registry remove issue

### ISSUE THREAD

**Issue by fearless359** [Samshal/Acl#8]
In order to get Samshal/Acl working on my system, I had to change the samshal/acl/src/Registry/Registry.php remove() method to return a bool rather than a void return, to get it working. The change is:
`
    /**
     * removes an object from the registry
     *
     * @param string $object
     * @return bool
     */
    public function remove(string $object) : bool
    {
        if ($this->exists($object)) {
            unset($this->registry[$object]);
        }

        return true;
    }
`

**Comment by Samshal** [comment]
Thanks @fearless359. I agree, returning bool values provides a much better mechanism for interoperability.
I would appreciated a PR, but I just committed these changes.

Just out of curiosity though, which version of PHP are you running this on?

**Comment by fearless359** [comment]
Thank you for the response. Not sure what a "PR" is. Please let me know.

**Comment by Samshal** [comment]
Ah ok. PR is acronym for Github [Pull Requests](https://github.community/t/what-is-pull-request/909/2).
